services:
  - type: web
    name: jansahayak
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python init_embeddings.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HF_HOME
        value: /opt/render/.cache/huggingface
    healthCheckPath: /
    autoDeploy: true
